### ISSUE TITLE
[BUG] 카테고리 화살표 클릭시에만 페이지가 이동

### ISSUE THREAD

**Issue by kowoohyuk** [woowa-techcamp-2021/store-2#173]
본문을 클릭했을 때는 페이지가 이동되지 않는데 혹시 의도한 사항인가요?!!

![image](https://user-images.githubusercontent.com/45394360/131074709-fa702fec-e807-499c-ab88-4e24afce9d73.png)

**Comment by negu63** [comment]
개선했어요~ 감사합니다!
