### ISSUE TITLE
[BUG] 마이페이지 주문 목록 date validation

### ISSUE THREAD

**Issue by eun-seong** [woowa-techcamp-2021/store-2#175]
## 개요 
마이페이지 주문 목록에 endDate가 start보다 빠른게 들어갑니다

## 버그 발생 단계 
![image](https://user-images.githubusercontent.com/49540564/131075423-c71f71f6-47f1-46eb-abd0-37b461bcd5c7.png)

## 진행 사항 

- [ ] todo1
- [ ] todo2

**Comment by yoonminsang** [comment]
#190
