### ISSUE TITLE
[BUG] 할인율 적용이 안됩니다!

### ISSUE THREAD

**Issue by dongqui** [woowa-techcamp-2021/store-2#176]
## 개요 
장바구니, 상세페이지에서 할인 적용이 안 된 가격으로 표기 됩니다!

## 버그 발생 단계 
[쎄일] 달린 상품 클릭시에 상세페이지, 장바구니에 할인 적용x 
## 진행 사항 

- [ ] todo1
- [ ] todo2

**Comment by yoonminsang** [comment]
#191
