### ISSUE TITLE
[BUG] 버그는 아니고 개선사항 제안합니다.

### ISSUE THREAD

**Issue by momongss** [woowa-techcamp-2021/store-2#182]
## 개요 
최하단까지 스크롤을 내리고 결제하기를 눌렀을 때 양식이 틀렸다는 메시지를 보기 힘듭니다.

## 버그 발생 단계 
![image](https://user-images.githubusercontent.com/37568161/131076474-84154118-6add-4058-b85a-4c8b11994c5a.png)

![image](https://user-images.githubusercontent.com/37568161/131076673-c032a638-6fe0-4571-bccc-ede7d7d922dd.png)

## 예상 동작 
- 결제하기 눌렀을 때 양식이 틀렸다면 모달창등으로 알려주면 좋을 것 같습니다!
- 아니면 양식 벨리데이션을 input 에 걸어줘도 좋을 것 같습니다.

**Comment by yoonminsang** [comment]
#190
