### ISSUE TITLE
[BUG] 장바구니 삭제 버그

### ISSUE THREAD

**Issue by chaeeun037** [woowa-techcamp-2021/store-2#186]
## 개요 
선택하지 않은 상품이 삭제되는 버그입니다. 

## 버그 발생 단계 
선택 후 상품 주문 -> 뒤로가기 -> 선택 상품삭제

https://user-images.githubusercontent.com/40158029/131077556-c7782d87-6418-44a6-a3d9-0a319040de7b.mov

## 진행 사항 

- [ ] todo1
- [ ] todo2

**Comment by negu63** [comment]
수정했습니다! 감사합니다~
