### ISSUE TITLE
[REFACTOR] 짝팀 리뷰 반영

### ISSUE THREAD

**Issue by Seogeurim** [woowa-techcamp-2021/store-2#19]
## 개요 

짝팀 기술 리뷰 및 코드 리뷰를 통해 개선할 부분을 반영합니다.

## 소요 시간 

- 예상 완료 시간 : 1h
- 실제 투입 시간 : 1h

## 진행 사항 

> 반영하지 않을 사항
> 
> - jsx에서 React import문 삭제 [참고](https://github.com/woowa-techcamp-2021/store-1/pull/12#discussion_r688273973)
> - css reset 라이브러리 [참고](https://github.com/woowa-techcamp-2021/store-2/pull/10#discussion_r688272127)
> - router 에서 type 관련 변경 [참고](https://github.com/woowa-techcamp-2021/store-2/pull/14#pullrequestreview-729301895)

- [x] webpack 설정에서 scss 삭제 [참고](https://github.com/woowa-techcamp-2021/store-2/pull/10#discussion_r688272224)
- [x] prettier 설정 변경 [참고](https://github.com/woowa-techcamp-2021/store-2/pull/10#discussion_r688269583)
- [x] clean webpack plugin 설정 변경 [참고](https://github.com/woowa-techcamp-2021/store-2/pull/10#discussion_r688270740)
- [x] css -> styled component

**Comment by TsooranKim** [comment]
#5 이거랑 #10 했어요!

**Comment by CurlyBat** [comment]
[#14](https://github.com/woowa-techcamp-2021/store-2/pull/14#pullrequestreview-729279507) 이거 했습니다~
라우터 진짜 잘만드셨어요 👍
