### ISSUE TITLE
[FEATURE] E3-S2 레이아웃 컴포넌트

### ISSUE THREAD

**Issue by Seogeurim** [woowa-techcamp-2021/store-2#29]
## 개요 

레이아웃 컴포넌트를 개발합니다.

## 소요 시간 

- 예상 완료 시간 : 4h
- 실제 투입 시간 : 7h

## 진행 사항 

- [x] 로고 컴포넌트
- [x] 헤더 컴포넌트
- [x] 푸터 컴포넌트
- [x] 레이아웃 컴포넌트
- [x] 상단 네브바
- [x] 반응형 스타일링

**Comment by Seogeurim** [comment]
지금 시작 !!!

**Comment by Seogeurim** [comment]
시간이 오래 걸린 이유 : 반응형, 테스트에 시간이 오래 걸렸다 !!

**Comment by KangyeolLee** [comment]
새벽코딩 멈춰!

**Comment by Seogeurim** [comment]
@KangyeolLee 아촤촤! 🤮🤮🤮
