### ISSUE TITLE
[PROJECT] E2-S2 ERD

### ISSUE THREAD

**Issue by yoonminsang** [woowa-techcamp-2021/store-2#3]
## 개요 

ERD를 작성합니다.

## 소요 시간 

- 예상 완료 시간 : 2h
- 실제 투입 시간 : 1h

## 진행 사항 

- [x] ERD 작성

**Comment by Seogeurim** [comment]
![image](https://user-images.githubusercontent.com/22045163/128980248-ed15e5bd-6289-43e0-9164-aef4e98b264e.png)
