### ISSUE TITLE
[BUG] React DOM 

### ISSUE THREAD

**Issue by edegiil** [woowa-techcamp-2021/store-2#64]
## 개요 
React DOM Property 문제

## 버그 발생 단계 
<img width="403" alt="스크린샷 2021-08-18 오전 11 15 24" src="https://user-images.githubusercontent.com/35324795/129825817-c8af86fb-d174-4be6-9c71-e6ca98fb2d36.png">

`woowahan-components`로 Props를 설정해줄 때 `camelCase`로 설정해주면 `React.createElement`를 하면서 자동으로 소문자로 바꿔주는 과정에서 발생하는 에러

## 예상 동작 
warning이 사라진다

## 진행 사항 

- [ ] ??

**Comment by yoonminsang** [comment]
해결
styledcomponent에 카멜케이스가 들어가는 경우를 적어주고 예외검사를 해서 해결
