### ISSUE TITLE
[FEATURE] E6-Sx 인풋 컴포넌트 확장

### ISSUE THREAD

**Issue by edegiil** [woowa-techcamp-2021/store-2#75]
## 개요 

인풋 컴포넌트를 여러곳에서 사용할 수 있도록 확장

## 소요 시간 

- 예상 완료 시간 : 1h
- 실제 투입 시간 : 

## 진행 사항 

- [ ] props 확장
- [ ] 기존 컴포넌트 교체

**Comment by Seogeurim** [comment]
추후 리팩토링 이슈에 포함합니다.
